#Import statements - Kept
import math
import pygame
import os


#Initializing pygame - Kept
pygame.init()


# Screen settings - Kept
Screen_info = pygame.display.Info()
WIDTH, HEIGHT = Screen_info.current_w, Screen_info.current_h
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Solar System Simulator")
clock = pygame.time.Clock()
FPS = 60


# font to be used for name tags - Kept
try:
    FONT = pygame.font.SysFont(None, 18)
except Exception:
    FONT = None


# Colors for anything i might need (generated by AI) - Kept
# ===== Original Colours =====
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
YELLOW = (255, 255, 0)
BLUE = (0, 0, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
ORANGE = (255, 165, 0)
CYAN = (0, 255, 255)

# ===== Extra varitions =====
BLACK_LIGHT = (20, 20, 20)
BLACK_DARK = (0, 0, 0)
CHARCOAL = (30, 30, 30)
JET_BLACK = (10, 10, 10)

WHITE_SMOKE = (245, 245, 245)
OFF_WHITE = (250, 250, 240)
IVORY = (255, 255, 240)
PEARL = (240, 240, 255)

YELLOW_LIGHT = (255, 255, 153)
YELLOW_PALE = (255, 255, 204)
YELLOW_GOLD = (255, 215, 0)
YELLOW_DARK = (204, 204, 0)

BLUE_LIGHT = (173, 216, 230)
BLUE_SKY = (135, 206, 235)
BLUE_DEEP = (0, 0, 139)
BLUE_NAVY = (0, 0, 128)
BLUE_ELECTRIC = (0, 80, 255)

GREEN_LIGHT = (144, 238, 144)
GREEN_LIME = (50, 205, 50)
GREEN_DARK = (0, 100, 0)
GREEN_NEON = (57, 255, 20)

RED_LIGHT = (255, 102, 102)
RED_DARK = (139, 0, 0)
RED_BLOOD = (200, 0, 0)
RED_ORANGE = (255, 69, 0)

ORANGE_LIGHT = (255, 200, 120)
ORANGE_DARK = (255, 140, 0)
ORANGE_BRIGHT = (255, 180, 0)
ORANGE_NEON = (255, 90, 0)

CYAN_LIGHT = (150, 255, 255)
CYAN_DARK = (0, 139, 139)
CYAN_AQUA = (0, 255, 200)
CYAN_DEEP = (0, 200, 255)

PURPLE = (128, 0, 128)
PURPLE_DARK = (75, 0, 130)
PURPLE_LIGHT = (200, 160, 255)

PINK = (255, 105, 180)
PINK_HOT = (255, 20, 147)
PINK_PASTEL = (255, 179, 186)

BROWN = (139, 69, 19)
BROWN_LIGHT = (181, 101, 29)
BROWN_DARK = (101, 67, 33)

GREY = (128, 128, 128)
GREY_LIGHT = (180, 180, 180)
GREY_DARK = (60, 60, 60)

LIGHT_BLUE = (173, 216, 230)
SKY_BLUE = (135, 206, 235)
DEEP_BLUE = (0, 0, 139)

LIGHT_GREEN = (144, 238, 144)
DARK_GREEN = (0, 100, 0)
NEON_GREEN = (57, 255, 20)

LIGHT_RED = (255, 102, 102)
DARK_RED = (139, 0, 0)

HOT_PINK = (255, 20, 147)
MAGENTA = (255, 0, 255)

LAVENDER = (230, 230, 250)
VIOLET = (138, 43, 226)

LIGHT_BROWN = (181, 101, 29)
DARK_BROWN = (101, 67, 33)

BEIGE = (245, 245, 220)
CREAM = (255, 253, 208)

GOLD = (255, 215, 0)
SILVER = (192, 192, 192)
BRONZE = (205, 127, 50)

AQUA = (0, 255, 200)

DARK_ORANGE = (255, 140, 0)
DARK_YELLOW = (204, 204, 0)

BLACK_BLUE = (10, 10, 40)
SPACE_GREY = (30, 30, 30)

PASTEL_BLUE = (174, 198, 207)
PASTEL_GREEN = (119, 221, 119)
PASTEL_PINK = (255, 179, 186)
PASTEL_PURPLE = (202, 160, 255)
PASTEL_YELLOW = (253, 253, 150)

NEON_BLUE = (0, 80, 255)
NEON_PINK = (255, 0, 120)
NEON_ORANGE = (255, 90, 0)
NEON_PURPLE = (190, 0, 255)

# ================================= Helper Functions ================================= #
def load_image_and_scale(name, size):
    #Load an image from Images/ and return a surface. If size is None, return original
    full_file_path = os.path.join('Images', name)
    try:
        loaded_image = pygame.image.load(full_file_path)
        if loaded_image.get_alpha() is None:
            loaded_image = loaded_image.convert()
        else:
            loaded_image = loaded_image.convert_alpha()
        if size is None:
            return loaded_image  # return original
        else:
            return pygame.transform.smoothscale(loaded_image, (size, size))
    except Exception as error_message:
        print(f"[Warning] Cannot load image: {full_file_path} -> {error_message}")
        return None

#Physical constants for gravitational simulation
GRAVITATIONAL_CONSTANT = 6.67430e-11  # Real G in m^3/(kgs^2)
SCALE_DISTANCE = 1e9 # 1 billion meters = 1 simulation unit
SCALE_MASS = 1e24 # 1e24 kg = 1 simulation mass unit
SCALE_TIME = 86400 # 1 day = 1 simulation time unit (for velocity calculations etc.)

#Derived constants
G = GRAVITATIONAL_CONSTANT * (SCALE_MASS * SCALE_TIME**2 / SCALE_DISTANCE**3) # G scaled to the simulation units


#Camera variables - Kept
camera_x, camera_y = 0, 0
camera_speed = 300
camera_zoom = 1.0
camera_zoom_max = 20
camera_zoom_min = 0.05


#Time management - Modified
SIM_TIME_MULTIPLIER = 86400.0 # How many seconds pass in the simulation each irl second
simulation_time = 0.0 # Start time
physics_substeps = 10 # New: Number of physics updates per frame

# ================================= Classes ================================= #

#Planet class structure
class Planet:
    def __init__(self, name, image_file, mass, position, velocity, size, color_fallback):
        self.name = name
        self.mass = mass
        self.color_fallback = color_fallback

        #Position and velocity as lists
        self.position = list(position) # [x, y] in world coordinates
        self.velocity = list(velocity) # [vx, vy] in units per sim-seconds
        self.acceleration = [0.0, 0.0] # Acceleration due to gravity etc. that will be calculated each frame

        #Trail system
        self.trail = [] # Will be a list of previous (x, y) position
        self.max_trail_length = 500 # Decides how many previous positions to keep

        #Display properties
        self.base_size = max(4, int(size))
        self.image_file = image_file

        #Image loading - Kept
        original_loaded_image = load_image_and_scale(image_file, None) # Function to be created
        self.original_image = original_loaded_image
        self._scaled_cache = {}
        if original_loaded_image is not None:
            self.image = pygame.transform.smoothscale(original_loaded_image, (self.base_size, self.base_size))
        else:
            self.image = None

    def calculate_gravitational_force(self, other_planet):
        """
        For calculating the gravitational force vector from other_planet acting on self
        """
        #Relative position vectors
        dx = other_planet.position[0] - self.position[0] # Change in x
        dy = other_planet.position[1] - self.position[1] # Change in y

        #Distance between planets calculated using pythagoras
        distance = math.sqrt((dx**2) + (dy**2)) # Pythagoras re-arranged for hypotenuse

        # Prevent division by zero
        if distance < 0.01:
            return [0.0, 0.0]

        #Calculating magnitude of force with Newtons law of gravitation: F = (G * m1 * m2) / r^2
        force_magnitude = (G * self.mass * other_planet.mass) / (distance**2)

        #Normalise the vector (dx, dy) nad multiply by force magnitude to make it proportional to both masses
        force_x = force_magnitude * (dx/ distance)
        force_y = force_magnitude * (dy/ distance)

        return [force_x, force_y]

    def update_physics(self, all_planets, dt): # all_planets - List of all planet objects (including sun), dt: Single time step in simulation seconds
        #Reset acceleration
        self.acceleration = [0.0, 0.0]

        #Calculate total force from all other bodies
        for planet in all_planets:
            if planet is not self: # Dont calculate force from itself
                force = self.calculate_gravitational_force(planet)

                # F = ma re-arranged to a = F/m
                self.acceleration[0] += force[0] / self.mass
                self.acceleration[1] += force[1] / self.mass

        # Velocity Verlet integration (more stable than euler) - to update position, acceleration and velocity at once
        # Update velocity: new_v = v + a * dt
        self.velocity[0] += self.acceleration[0] * dt
        self.velocity[1] += self.acceleration[1] * dt

        # Update position: new_p = p + v * dt
        self.position[0] += self.velocity[0] * dt
        self.position[1] += self.velocity[1] * dt

        # Add current position to the list of trail positions (every few frames)
        if len(self.trail) == 0 or (self.position[0] - self.trail[-1][0])**2 + (self.position[1] - self.trail[-1][1])**2 > 1.0: # Condition only allows a trail to be placed if object has moved > 1 unit
            self.trail.append((self.position[0], self.position[1]))

        # Limit trail length
        if len(self.trail) > self.max_trail_length:
            self.trail.pop(0) # Remove oldest trail position

    def draw(self, screen, camera_offset_x, camera_offset_y, zoom_level, draw_trail = True): # Draw planet and its orbital trail
        # Draw the trail first
        if draw_trail and len(self.trail) > 2:
            trail_points = []
            for trail_x, trail_y in self.trail:
                screen_x = int(WIDTH // 2 + (trail_x - camera_offset_x) * zoom_level)
                screen_y = int(HEIGHT // 2 + (trail_y - camera_offset_y) * zoom_level)
                trail_points.append((screen_x, screen_y))

            # Draw trail as connected lines
            if len(trail_points) > 1:
                try:
                    pygame.draw.lines(screen, self.color_fallback, False, trail_points, 1)
                except:
                    pass # Carry on if the points are off screen

        # Calculate the planet's screen position (using self.position instead of self.x/y)
        screen_x = int(WIDTH // 2 + (self.position[0] - camera_offset_x) * zoom_level)
        screen_y = int(HEIGHT // 2 + (self.position[1] - camera_offset_y) * zoom_level)

        # Calculate the display size
        desired_planet_size = max(2, int(self.base_size * zoom_level))

        if desired_planet_size < 1:
            return

        # Image drawing (same as old code)
        image_source = getattr(self, 'original_image', None) or self.image

        if image_source is not None:
            cached_scaled_image = self._scaled_cache.get(desired_planet_size)
            if cached_scaled_image is None:
                try:
                    scaled_planet_image = pygame.transform.smoothscale(image_source, (desired_planet_size, desired_planet_size))
                except Exception:
                    scaled_planet_image = pygame.transform.scale(image_source, (desired_planet_size, desired_planet_size))
                self._scaled_cache[desired_planet_size] = scaled_planet_image
                cached_scaled_image = scaled_planet_image

            planet_image_rect = cached_scaled_image.get_rect(center = (screen_x, screen_y))
            screen.blit(cached_scaled_image, planet_image_rect)

        else:
            # Circle generation as a fallback in case of error using color_fallback
            pygame.draw.circle(screen, self.color_fallback, (screen_x, screen_y), desired_planet_size // 2)

        # Draw name tag (same as old code)
        try:
            self.name_tag_draw(screen, screen_x, screen_y, desired_planet_size)
        except Exception:
            pass

    def name_tag_draw(self, screen, screen_x, screen_y, planet_size):
        #Draw a small label under the planet
        font = globals().get('FONT', None)
        if not font:
            return
        try:
            text_surface = font.render(self.name, True, WHITE)
            text_rectangle = text_surface.get_rect(center=(screen_x, screen_y + planet_size // 2 + 10))
            background_rectangle = text_rectangle.inflate(4, 2)
            pygame.draw.rect(screen, BLACK, background_rectangle)
            screen.blit(text_surface, text_rectangle)
        except Exception:
            return

# ================================= External  functions ================================= #
def calculate_circular_orbit_velocity(distance_from_sun, sun_mass):
    # Calculate the velocity that is needed for a circular orbit at its distance
    # For a circular orbit : v = root(GxM/r), where v is the tangential velocity
    return math.sqrt(G * sun_mass / distance_from_sun)

# ================================= Solar system data ================================= #

# Sun data
SUN_MASS_KG = 1.989e30 # In Kg
SUN_RADIUS_KM = 696000 # In Km

# Planet data: [mass_kg, distance_au, radius_km, color_rgb]
PLANET_DATA = {
    "Mercury": [3.285e23, 0.387, 2439.7, (169, 169, 169)],
    "Venus":   [4.867e24, 0.723, 6051.8, (255, 198, 73)],
    "Earth":   [5.972e24, 1.000, 6371.0, (100, 149, 237)],
    "Mars":    [6.39e23,  1.524, 3389.5, (193, 68, 14)],
    "Jupiter": [1.898e27, 5.203, 69911,  (201, 176, 55)],
    "Saturn":  [5.683e26, 9.537, 58232,  (249, 214, 46)],
    "Uranus":  [8.681e25, 19.19, 25362,  (79, 208, 231)],
    "Neptune": [1.024e26, 30.07, 24622,  (63, 84, 186)],
}

# Conversion from Astronomical unit to meters
AU_TO_METERS = 1.496e11

# Convert to simulation units
sun_mass_sim = SUN_MASS_KG / SCALE_MASS
sun_size_pixels = 20

# Creating the sun
sun = Planet(name="Sun", image_file = "sun.png", mass = sun_mass_sim, position = [0,0], velocity = [0,0], size = sun_size_pixels, color_fallback = YELLOW)

# Creating planets
celestial_bodies = [sun] # Only have the sun in the list by default
planets_only = [] # Seperate list without sun only used for specfic operations

for planet_name, (mass_kg, distance_au, radius_km, color) in PLANET_DATA.items():
    # Convert to units used in the sim
    mass_sim = mass_kg / SCALE_MASS
    distance_sim = (distance_au * AU_TO_METERS) / SCALE_DISTANCE

    # Calculate display size (using log so that small planets are visible
    size_pixels = max(4, int(5 * math.log10(radius_km / 1000)))

    # Calculate orbital velocity for circular orbit
    orbital_speed = calculate_circular_orbit_velocity(distance_sim, sun_mass_sim)

    # Initial position (on the right of the sun at the individual distances of the planets)
    initial_position = [distance_sim, 0]

    # Initial velocity: perpendicular to radius (upwards for counter-clockwise orbit)
    initial_velocity = [0, orbital_speed]

    planet = Planet(name = planet_name, image_file = f"{planet_name}.png", mass = mass_sim, position = initial_position, velocity = initial_velocity, size = size_pixels, color_fallback = color)
    celestial_bodies.append(planet)
    planets_only.append(planet)

# Easy access
mercury = planets_only[0]
venus = planets_only[1]
earth = planets_only[2]
mars = planets_only[3]
jupiter = planets_only[4]
saturn = planets_only[5]
uranus = planets_only[6]
neptune = planets_only[7]


# ================================= Main Game Loop ================================= #
running = True
paused_multiplier = SIM_TIME_MULTIPLIER  # For pause functionality

while running:
    screen.fill(BLACK)

    # Calculate delta time
    raw_delta_time = clock.tick(FPS) / 1000.0
    delta_time = 1.0 / FPS  # Fixed timestep

    # Accumulate simulation time
    simulation_time += delta_time * SIM_TIME_MULTIPLIER

    # Event handling
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE:
                running = False
            # Speed controls
            elif event.key in (pygame.K_LSHIFT, pygame.K_RSHIFT):
                SIM_TIME_MULTIPLIER *= 1.5
            elif event.key in (pygame.K_LCTRL, pygame.K_RCTRL):
                SIM_TIME_MULTIPLIER /= 1.5
            elif event.key == pygame.K_SPACE:
                # Pause/unpause
                if SIM_TIME_MULTIPLIER > 0:
                    paused_multiplier = SIM_TIME_MULTIPLIER
                    SIM_TIME_MULTIPLIER = 0
                else:
                    SIM_TIME_MULTIPLIER = paused_multiplier
            # Clear trails
            elif event.key == pygame.K_t:
                for planet in planets_only:
                    planet.trail.clear()
            # Camera focus on planets
            elif event.key == pygame.K_1:
                camera_x, camera_y = mercury.position[0], mercury.position[1]
            elif event.key == pygame.K_2:
                camera_x, camera_y = venus.position[0], venus.position[1]
            elif event.key == pygame.K_3:
                camera_x, camera_y = earth.position[0], earth.position[1]
            elif event.key == pygame.K_4:
                camera_x, camera_y = mars.position[0], mars.position[1]
            elif event.key == pygame.K_5:
                camera_x, camera_y = jupiter.position[0], jupiter.position[1]
            elif event.key == pygame.K_6:
                camera_x, camera_y = saturn.position[0], saturn.position[1]
            elif event.key == pygame.K_7:
                camera_x, camera_y = uranus.position[0], uranus.position[1]
            elif event.key == pygame.K_8:
                camera_x, camera_y = neptune.position[0], neptune.position[1]
            elif event.key == pygame.K_0:
                camera_x, camera_y = 0, 0  # Focus on sun
        # Mouse wheel zoom
        elif event.type == pygame.MOUSEWHEEL:
            if event.y > 0:
                camera_zoom *= 1.1
            else:
                camera_zoom /= 1.1

    # Clamp zoom
    camera_zoom = max(camera_zoom_min, min(camera_zoom_max, camera_zoom))

    # Camera movement
    keys = pygame.key.get_pressed()
    adjusted_pan_speed = camera_speed / camera_zoom

    if keys[pygame.K_LEFT] or keys[pygame.K_a]:
        camera_x -= adjusted_pan_speed * delta_time
    if keys[pygame.K_RIGHT] or keys[pygame.K_d]:
        camera_x += adjusted_pan_speed * delta_time
    if keys[pygame.K_UP] or keys[pygame.K_w]:
        camera_y -= adjusted_pan_speed * delta_time
    if keys[pygame.K_DOWN] or keys[pygame.K_s]:
        camera_y += adjusted_pan_speed * delta_time

    # Physics update loop with substeps
    substep_dt = (delta_time * SIM_TIME_MULTIPLIER) / physics_substeps

    for _ in range(physics_substeps):
        for planet in planets_only:
            planet.update_physics(celestial_bodies, substep_dt)

    # Draw sun
    sun_screen_x = int(WIDTH // 2 + (sun.position[0] - camera_x) * camera_zoom)
    sun_screen_y = int(HEIGHT // 2 + (sun.position[1] - camera_y) * camera_zoom)
    desired_sun_size = max(2, int(sun.base_size * camera_zoom))

    if sun.original_image is not None:
        cached_sun_image = sun._scaled_cache.get(desired_sun_size)
        if cached_sun_image is None:
            try:
                cached_sun_image = pygame.transform.smoothscale(
                    sun.original_image, (desired_sun_size, desired_sun_size))
            except Exception:
                cached_sun_image = pygame.transform.scale(
                    sun.original_image, (desired_sun_size, desired_sun_size))
            sun._scaled_cache[desired_sun_size] = cached_sun_image

        sun_rect = cached_sun_image.get_rect(center=(sun_screen_x, sun_screen_y))
        screen.blit(cached_sun_image, sun_rect)
    else:
        pygame.draw.circle(screen, YELLOW, (sun_screen_x, sun_screen_y), desired_sun_size // 2)

    if FONT:
        try:
            sun.name_tag_draw(screen, sun_screen_x, sun_screen_y, desired_sun_size)
        except:
            pass

    # Draw all planets
    for body in celestial_bodies:
        body.draw(screen, camera_x, camera_y, camera_zoom, draw_trail=True)

    # Time display
    if FONT:
        speed_scale_factor = SIM_TIME_MULTIPLIER / 86400.0
        time_seconds = int(simulation_time)
        time_minutes = round(time_seconds / 60, 2)
        time_hours = round(time_minutes / 60, 2)
        time_days = round(time_hours / 24, 2)
        time_years = round(time_days / 365.25, 2)

        time_display_text = [
            "Seconds: " + str(time_seconds),
            "Minutes: " + str(time_minutes),
            "Hours:   " + str(time_hours),
            "Days:    " + str(time_days),
            "Years:   " + str(time_years),
            "Speed:   " + str(round(speed_scale_factor, 1)) + "x"
        ]

        text_position = 20
        for line in time_display_text:
            text_surf = FONT.render(line, True, BLACK)
            text_rect = text_surf.get_rect(center=(65, text_position))
            bg_rect = text_rect.inflate(4, 2)
            pygame.draw.rect(screen, WHITE, bg_rect)
            screen.blit(text_surf, text_rect)
            text_position += 25

    pygame.display.flip()

pygame.quit()
